Revert "repo: remove symlinks to libc. (#1100)" (#1146)
This reverts commit 3052b0f459ded440dad2e2362946ee37e09c8606.

This commit causes:
/usr/bin/ld: ./.libs/libNetworkManager.a(nm-vpn-editor-plugin.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/build/network-manager-daily/parts/networkmanager/install/lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

LP: #1665089