fix(snap): add missing build-packages for git
::       src/types.h:36:2: error: #error You need a compatible libgit2 version (1.7.x)
::          36 | #error You need a compatible libgit2 version (1.7.x)

Match version with table on
https://www.pygit2.org/install.html#version-numbers

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>