cli: add missing argument to click.BadOptionUsage()
Missing option_name parameter.  Caught by mypy uprev.

Add type: ignore here because mypy reports a false positive:
snapcraft/cli/remote.py:236: error: Argument 2 to "BadOptionUsage" has incompatible type "str"; expected "Optional[Context]"

This is fixed in newer mypy, so we'll remove that after
mypy is updated.  Add TODO to for reference.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>