rust plugin: fix linker on i386
On i386 environment, linker becomes i386-linux-gnu-gcc according to
arch_triplet. It causes the following error on build.snapcraft.io:

error: linker `i386-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)

To fix it, I added _get_linker method to adjust linker name.