error: Item "None" of "Optional[Any]" has no attribute "execute"
`self._ensure_container_running()` does the required None check,
but `mypy` doesn't look that deep