meta: fix typing error in ContentPlug's from_dict()
Get "target".  If None, raise error.  Then mypy knows
that the target is a string, and no longer optional.

Addresses mypy uprev error:

```
snapcraft/internal/meta/plugs.py:146: error: Argument "target" to "ContentPlug" has incompatible type "Optional[str]"; expected "str"
```

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>