fix(unsquashfs): fix Fatal Error when using unsquashfs
When trying to push a big snap, snapcraft fails with the error

    FATAL ERROR: Data queue size is too large

This is a bug in unsquashfs tool 4.5. But it has been fixed in
4.6.1, the current stable.

This patch builds squashfs-tools version 4.6.1 from the GIT
repository, thus fixing this problem.

Fix https://github.com/canonical/snapcraft/issues/5132