tests: skip spread tests for rust on s390x
The stable toolchain is missing components in order to correctly test:

    error: some components unavailable for download for channel stable: 'clippy', 'rustfmt'

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>