project: add fallbacks for os.sched_getaffinity (#2963)
Project was recently updated [1] to use os.sched_getaffinity()
to get a more accurate view of how many threads are available
for use.

However, OSX does not implement os.sched_getaffinity(), failing
with AttributeError.

Fall back to multiprocessing.cpu_count if os.sched_getaffinity()
does not exist.

Failing that, return 1.

Add a couple of unit tests for coverage.

[1] 332df0f97e93ac7ecc325f929faacb79ae55ddd1

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>