conda plugin: simplify source url/checksum handling
Replace _MINICONDA_URL and _MINICONDA_UNKNOWN_URL dictionaries
with a helper function using a single format string
and dictionary to lookup known checksums.

This is motivated by an uprev of mypy which stumbles on
the type checking:

```
snapcraft/plugins/conda.py:111:
 error: Item "None" of "Optional[str]" has no attribute "format"
snapcraft/plugins/conda.py:116:
 error: Value of type "object" is not indexable
snapcraft/plugins/conda.py:118:
 error: Value of type "object" is not indexable
```

This helper was introduced as `_get_miniconda_source()`, and
CondaPlugin's method was renamed to `_get_miniconda_script()`
to better indicate its behavior.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>