rust plugin: set rustup profile to minimal
On some environment, some components can't be downloaded by rustup.
It causes the following error on build.snapcraft.io:

error: some components unavailable for download for channel stable:
'clippy', 'rustfmt'

To fix it, I set profile to minimal.
If profile is minimal, 'clippy' and 'rustfmt' will be skipped.