Remove trailing slash from staging  STORE_UPLOAD_URL.
The trailing slash results in:

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

because the upload path contains a double slash, in the server logs we
see:

POST //unscanned-upload/ HTTP/1.1...