project_loader: use -isystem instead of -I for system include paths
Warnings are ignored for sytem includes.  However, when a system
include gets installed to staging directory, the user may be
issued warnings (errors if -Werror) because snapcraft is adding
include paths thats include these system headers.

Use `-isystem` rather than `-I` to add system include paths to
the default compiler flags.  The other option is to use `-idirafter`,
but is more likely to affect current builds by changing the order
of the search paths.

For example:
```
In file included from /root/parts/workspace/install/usr/include/x86_64-linux-gnu/bits/fcntl.h:61:0,
from /root/parts/workspace/install/usr/include/fcntl.h:35,
from /root/parts/workspace/build/benchmark_catkin/benchmark_src-prefix/src/benchmark_src/src/sysinfo.cc:23:
/root/parts/workspace/install/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h:355:27: error: ISO C++ forbids zero-size array ‘f_handle’ [-Wpedantic]
unsigned char f_handle[0];
```

See:

[1] https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

> The header files declaring interfaces to the operating system and runtime libraries often cannot be written in strictly conforming C. Therefore, GCC gives code found in system headers special treatment. All warnings, other than those generated by ‘#warning’ (see Diagnostics), are suppressed while GCC is processing a system header.

[2] https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html

> The -isystem and -idirafter options also mark the directory as a system directory, so that it gets the same special treatment that is applied to the standard system directories.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>